name: "CI - Test Dev Container Features"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        features:
          - bun
        baseImage:
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:debian
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run tests - ${{ matrix.features }} on ${{ matrix.baseImage }}"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        features:
          - bun
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run scenario tests - ${{ matrix.features }}"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .
